services:
  giropops-senhas:
    build:
      context: ./app
    container_name: devops-backend
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    volumes:
      - /mnt/persist-data/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
#teste para o actions
